version: '3'
services:
  db: 
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: RM95177
      POSTGRES_PASSWORD: 210104
      POSTGRES_DB: db
    volumes:
      - ./data:/var/lib/postgresql/data
  app:
    build: .
    command: python app.py
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
