# Use a imagem oficial do PostgreSQL como base
FROM postgres

# Defina as variáveis de ambiente para configurar o banco de dados
ENV POSTGRES_USER=RM95177
ENV POSTGRES_PASSWORD=210104
ENV POSTGRES_DB=mydb
